# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

'''
    WASec – a software that performs automated tests on websites and scan them for SQL Injection and Cross-site Scripting Vulnerabilites.
    Copyright (c) 2018, Inass Husien.

    WASec is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation, either version 2 of the License or (at your option) any later version.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along with this program.
    If not, see <http://www.gnu.org/licenses/>

    You can contact us at e.ismail@it.misuratau.edu.ly
'''

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(595, 600))
        MainWindow.setMaximumSize(QtCore.QSize(595, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(60, 60))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(130, -30, 341, 291))
        self.graphicsView.setStyleSheet("background: url(gui/logoWORDS.png);\n"
"background-repeat: no;\n"
"border: none;")
        self.graphicsView.setInteractive(False)
        self.graphicsView.setAlignment(QtCore.Qt.AlignCenter)
        self.graphicsView.setObjectName("graphicsView")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(-20, 220, 631, 297))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(15)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblburl = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblburl.setMinimumSize(QtCore.QSize(100, 20))
        self.lblburl.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblburl.setFont(font)
        self.lblburl.setTextFormat(QtCore.Qt.AutoText)
        self.lblburl.setObjectName("lblburl")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblburl)
        self.tbbaseURL = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbbaseURL.sizePolicy().hasHeightForWidth())
        self.tbbaseURL.setSizePolicy(sizePolicy)
        self.tbbaseURL.setMinimumSize(QtCore.QSize(420, 25))
        self.tbbaseURL.setMaximumSize(QtCore.QSize(420, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tbbaseURL.setFont(font)
        self.tbbaseURL.setMouseTracking(True)
        self.tbbaseURL.setTabletTracking(True)
        self.tbbaseURL.setToolTipDuration(1)
        self.tbbaseURL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tbbaseURL.setText("")
        self.tbbaseURL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tbbaseURL.setObjectName("tbbaseURL")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tbbaseURL)
        self.lbllurl = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbllurl.setMinimumSize(QtCore.QSize(100, 20))
        self.lbllurl.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbllurl.setFont(font)
        self.lbllurl.setTextFormat(QtCore.Qt.AutoText)
        self.lbllurl.setObjectName("lbllurl")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbllurl)
        self.tbloginURL = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbloginURL.sizePolicy().hasHeightForWidth())
        self.tbloginURL.setSizePolicy(sizePolicy)
        self.tbloginURL.setMinimumSize(QtCore.QSize(420, 25))
        self.tbloginURL.setMaximumSize(QtCore.QSize(420, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tbloginURL.setFont(font)
        self.tbloginURL.setMouseTracking(True)
        self.tbloginURL.setTabletTracking(True)
        self.tbloginURL.setToolTipDuration(1)
        self.tbloginURL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tbloginURL.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.tbloginURL.setText("")
        self.tbloginURL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tbloginURL.setObjectName("tbloginURL")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tbloginURL)
        self.lblroburl = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblroburl.setMinimumSize(QtCore.QSize(120, 20))
        self.lblroburl.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblroburl.setFont(font)
        self.lblroburl.setTextFormat(QtCore.Qt.AutoText)
        self.lblroburl.setObjectName("lblroburl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblroburl)
        self.tbrobURL = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbrobURL.sizePolicy().hasHeightForWidth())
        self.tbrobURL.setSizePolicy(sizePolicy)
        self.tbrobURL.setMinimumSize(QtCore.QSize(420, 25))
        self.tbrobURL.setMaximumSize(QtCore.QSize(420, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tbrobURL.setFont(font)
        self.tbrobURL.setMouseTracking(True)
        self.tbrobURL.setTabletTracking(True)
        self.tbrobURL.setToolTipDuration(1)
        self.tbrobURL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tbrobURL.setText("")
        self.tbrobURL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tbrobURL.setObjectName("tbrobURL")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tbrobURL)
        self.lbloptionts = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbloptionts.setMinimumSize(QtCore.QSize(105, 20))
        self.lbloptionts.setMaximumSize(QtCore.QSize(105, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbloptionts.setFont(font)
        self.lbloptionts.setTextFormat(QtCore.Qt.AutoText)
        self.lbloptionts.setObjectName("lbloptionts")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbloptionts)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(15)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rbfull = QtWidgets.QRadioButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbfull.sizePolicy().hasHeightForWidth())
        self.rbfull.setSizePolicy(sizePolicy)
        self.rbfull.setMinimumSize(QtCore.QSize(75, 20))
        self.rbfull.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rbfull.setFont(font)
        self.rbfull.setObjectName("rbfull")
        self.gridLayout_4.addWidget(self.rbfull, 1, 4, 1, 1)
        self.rbxss = QtWidgets.QRadioButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbxss.sizePolicy().hasHeightForWidth())
        self.rbxss.setSizePolicy(sizePolicy)
        self.rbxss.setMinimumSize(QtCore.QSize(80, 20))
        self.rbxss.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rbxss.setFont(font)
        self.rbxss.setObjectName("rbxss")
        self.gridLayout_4.addWidget(self.rbxss, 1, 2, 1, 1)
        self.rbcrawl = QtWidgets.QRadioButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbcrawl.sizePolicy().hasHeightForWidth())
        self.rbcrawl.setSizePolicy(sizePolicy)
        self.rbcrawl.setMinimumSize(QtCore.QSize(80, 20))
        self.rbcrawl.setMaximumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rbcrawl.setFont(font)
        self.rbcrawl.setObjectName("rbcrawl")
        self.gridLayout_4.addWidget(self.rbcrawl, 1, 0, 1, 1)
        self.rbsql = QtWidgets.QRadioButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbsql.sizePolicy().hasHeightForWidth())
        self.rbsql.setSizePolicy(sizePolicy)
        self.rbsql.setMinimumSize(QtCore.QSize(130, 20))
        self.rbsql.setMaximumSize(QtCore.QSize(130, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rbsql.setFont(font)
        self.rbsql.setObjectName("rbsql")
        self.gridLayout_4.addWidget(self.rbsql, 1, 1, 1, 1)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.gridLayout_4)
        self.lblcrawlmax = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblcrawlmax.setMinimumSize(QtCore.QSize(120, 20))
        self.lblcrawlmax.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblcrawlmax.setFont(font)
        self.lblcrawlmax.setTextFormat(QtCore.Qt.AutoText)
        self.lblcrawlmax.setObjectName("lblcrawlmax")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lblcrawlmax)
        self.sbmaxcrawl = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.sbmaxcrawl.setMinimumSize(QtCore.QSize(55, 25))
        self.sbmaxcrawl.setMaximumSize(QtCore.QSize(55, 25))
        self.sbmaxcrawl.setObjectName("sbmaxcrawl")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sbmaxcrawl)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(370, 470, 211, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.btnclear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnclear.setMinimumSize(QtCore.QSize(80, 35))
        self.btnclear.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnclear.setFont(font)
        self.btnclear.setStyleSheet("border-radius: 5px;\n"
"background-color:orange;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnclear.setObjectName("btnclear")
        self.gridLayout_8.addWidget(self.btnclear, 0, 1, 1, 1)
        self.btnstart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnstart.setMinimumSize(QtCore.QSize(80, 35))
        self.btnstart.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnstart.setFont(font)
        self.btnstart.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(0, 170, 255);\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;\n"
"Cursor:pointer;")
        self.btnstart.setObjectName("btnstart")
        self.gridLayout_8.addWidget(self.btnstart, 0, 0, 1, 1)
        self.lblstate = QtWidgets.QLabel(self.centralwidget)
        self.lblstate.setGeometry(QtCore.QRect(220, 440, 503, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblstate.setFont(font)
        self.lblstate.setStyleSheet("color:red;")
        self.lblstate.setText("")
        self.lblstate.setObjectName("lblstate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 520, 441, 41))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 595, 21))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout_WASec = QtWidgets.QAction(MainWindow)
        self.actionAbout_WASec.setObjectName("actionAbout_WASec")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuProject.addAction(self.actionAbout_WASec)
        self.menuProject.addAction(self.actionExit)
        self.menubar.addAction(self.menuProject.menuAction())

        self.retranslateUi(MainWindow)
        self.btnclear.clicked.connect(self.tbbaseURL.clear)
        self.btnclear.clicked.connect(self.sbmaxcrawl.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tbbaseURL, self.tbloginURL)
        MainWindow.setTabOrder(self.tbloginURL, self.tbrobURL)
        MainWindow.setTabOrder(self.tbrobURL, self.rbcrawl)
        MainWindow.setTabOrder(self.rbcrawl, self.rbxss)
        MainWindow.setTabOrder(self.rbxss, self.rbfull)
        MainWindow.setTabOrder(self.rbfull, self.sbmaxcrawl)
        MainWindow.setTabOrder(self.sbmaxcrawl, self.btnstart)
        MainWindow.setTabOrder(self.btnstart, self.btnclear)
        MainWindow.setTabOrder(self.btnclear, self.graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WASec - Misurata University"))
        self.lblburl.setText(_translate("MainWindow", "Base URL"))
        self.tbbaseURL.setToolTip(_translate("MainWindow", "Root website URL"))
        self.tbbaseURL.setWhatsThis(_translate("MainWindow", "Target website URL"))
        self.tbbaseURL.setAccessibleName(_translate("MainWindow", "tbBaseURL"))
        self.tbbaseURL.setPlaceholderText(_translate("MainWindow", "e.g. http://www.example.com/"))
        self.lbllurl.setText(_translate("MainWindow", "Login URL"))
        self.tbloginURL.setToolTip(_translate("MainWindow", "Root website URL"))
        self.tbloginURL.setWhatsThis(_translate("MainWindow", "Login Page URL"))
        self.tbloginURL.setAccessibleName(_translate("MainWindow", "tbLoginURL"))
        self.tbloginURL.setPlaceholderText(_translate("MainWindow", "e.g. http://www.example.com/login.php"))
        self.lblroburl.setText(_translate("MainWindow", "Robots.txt URL"))
        self.tbrobURL.setToolTip(_translate("MainWindow", "Root website URL"))
        self.tbrobURL.setWhatsThis(_translate("MainWindow", "Login Page URL"))
        self.tbrobURL.setAccessibleName(_translate("MainWindow", "tbLoginURL"))
        self.tbrobURL.setPlaceholderText(_translate("MainWindow", "e.g. http://www.example.com/robots.txt"))
        self.lbloptionts.setText(_translate("MainWindow", "Scan Options"))
        self.rbfull.setWhatsThis(_translate("MainWindow", "Test for both SQLi and XSS"))
        self.rbfull.setText(_translate("MainWindow", "Full scan"))
        self.rbxss.setWhatsThis(_translate("MainWindow", "Test for Cross-site Scripting"))
        self.rbxss.setText(_translate("MainWindow", "XSS scan"))
        self.rbcrawl.setWhatsThis(_translate("MainWindow", "Get all links in website"))
        self.rbcrawl.setText(_translate("MainWindow", "Crawl only"))
        self.rbsql.setWhatsThis(_translate("MainWindow", "Test for SQL Injection"))
        self.rbsql.setText(_translate("MainWindow", "SQL Injection scan"))
        self.lblcrawlmax.setText(_translate("MainWindow", "Pages to Crawl"))
        self.sbmaxcrawl.setWhatsThis(_translate("MainWindow", "Number of pages to crawl"))
        self.btnclear.setWhatsThis(_translate("MainWindow", "Clear all fields"))
        self.btnclear.setText(_translate("MainWindow", "Clear"))
        self.btnstart.setWhatsThis(_translate("MainWindow", "Scan your website!"))
        self.btnstart.setText(_translate("MainWindow", "Start!"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#5500ff;\">WASec is an open-source software developed under the GPL licence - 2018</span></p></body></html>"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout_WASec.setText(_translate("MainWindow", "About WASec"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

