# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):

    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(688, 516)
        MainWindow2.setMinimumSize(QtCore.QSize(688, 516))
        MainWindow2.setMaximumSize(QtCore.QSize(688, 516))
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 100, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(1)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:rgb(240, 240, 240);")
        self.tabWidget.setObjectName("tabWidget")
        self.tabcrawl = QtWidgets.QWidget()
        self.tabcrawl.setObjectName("tabcrawl")
        self.treeView = QtWidgets.QTreeView(self.tabcrawl)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 641, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(641, 271))
        self.treeView.setMaximumSize(QtCore.QSize(641, 271))
        self.treeView.setStyleSheet("background:white;")
        self.treeView.setObjectName("treeView")
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setHeaderHidden(True)
        self.btncancel = QtWidgets.QPushButton(self.tabcrawl)
        self.btncancel.setGeometry(QtCore.QRect(550, 280, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncancel.sizePolicy().hasHeightForWidth())
        self.btncancel.setSizePolicy(sizePolicy)
        self.btncancel.setMinimumSize(QtCore.QSize(80, 35))
        self.btncancel.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btncancel.setFont(font)
        self.btncancel.setStyleSheet("border-radius: 5px;\n"
                                     "background-color:red;\n"
                                     "color:white;\n"
                                     "font-weight:bold;\n"
                                     "font-size: 13px;\n"
                                     "margin-bottom:5px;")
        self.btncancel.setObjectName("btncancel")
        self.lblstate_crawl = QtWidgets.QLabel(self.tabcrawl)
        self.lblstate_crawl.setGeometry(QtCore.QRect(10, 290, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblstate_crawl.setFont(font)
        self.lblstate_crawl.setStyleSheet("color:blue;")
        self.lblstate_crawl.setObjectName("lblstate_crawl")
        self.lblshow_state = QtWidgets.QLabel(self.tabcrawl)
        self.lblshow_state.setGeometry(QtCore.QRect(70, 290, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblshow_state.setFont(font)
        self.lblshow_state.setText("")
        self.lblshow_state.setObjectName("lblshow_state")
        self.tabWidget.addTab(self.tabcrawl, "")
        self.tabsqli = QtWidgets.QWidget()
        self.tabsqli.setObjectName("tabsqli")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabsqli)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 641, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btncancel_2 = QtWidgets.QPushButton(self.tabsqli)
        self.btncancel_2.setGeometry(QtCore.QRect(540, 280, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncancel_2.sizePolicy().hasHeightForWidth())
        self.btncancel_2.setSizePolicy(sizePolicy)
        self.btncancel_2.setMinimumSize(QtCore.QSize(80, 35))
        self.btncancel_2.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btncancel_2.setFont(font)
        self.btncancel_2.setStyleSheet("border-radius: 5px;\n"
                                       "background-color:red;\n"
                                       "color:white;\n"
                                       "font-weight:bold;\n"
                                       "font-size: 13px;")
        self.btncancel_2.setObjectName("btncancel_2")
        self.lbltotal = QtWidgets.QLabel(self.tabsqli)
        self.lbltotal.setGeometry(QtCore.QRect(530, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbltotal.setFont(font)
        self.lbltotal.setObjectName("lbltotal")
        self.lblpname = QtWidgets.QLabel(self.tabsqli)
        self.lblpname.setGeometry(QtCore.QRect(50, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblpname.setFont(font)
        self.lblpname.setObjectName("lblpname")
        self.pbpages = QtWidgets.QProgressBar(self.tabsqli)
        self.pbpages.setGeometry(QtCore.QRect(50, 140, 531, 31))
        self.pbpages.setProperty("value", 24)
        self.pbpages.setObjectName("pbpages")
        self.pbtotal = QtWidgets.QProgressBar(self.tabsqli)
        self.pbtotal.setGeometry(QtCore.QRect(50, 240, 531, 31))
        self.pbtotal.setProperty("value", 24)
        self.pbtotal.setObjectName("pbtotal")
        self.lblpsp = QtWidgets.QLabel(self.tabsqli)
        self.lblpsp.setGeometry(QtCore.QRect(50, 110, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblpsp.setFont(font)
        self.lblpsp.setObjectName("lblpsp")
        self.lbltsp = QtWidgets.QLabel(self.tabsqli)
        self.lbltsp.setGeometry(QtCore.QRect(50, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltsp.setFont(font)
        self.lbltsp.setObjectName("lbltsp")
        self.lbltargetsql = QtWidgets.QLabel(self.tabsqli)
        self.lbltargetsql.setGeometry(QtCore.QRect(50, 60, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(11)
        self.lbltargetsql.setFont(font)
        self.lbltargetsql.setText("")
        self.lbltargetsql.setObjectName("lbltargetsql")
        self.lblsno = QtWidgets.QLabel(self.tabsqli)
        self.lblsno.setGeometry(QtCore.QRect(370, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblsno.setFont(font)
        self.lblsno.setObjectName("lblsno")
        self.lblvul = QtWidgets.QLabel(self.tabsqli)
        self.lblvul.setGeometry(QtCore.QRect(370, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblvul.setFont(font)
        self.lblvul.setObjectName("lblvul")
        self.tabWidget.addTab(self.tabsqli, "")
        self.tabxss = QtWidgets.QWidget()
        self.tabxss.setObjectName("tabxss")
        self.lblsno_2 = QtWidgets.QLabel(self.tabxss)
        self.lblsno_2.setGeometry(QtCore.QRect(370, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblsno_2.setFont(font)
        self.lblsno_2.setObjectName("lblsno_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabxss)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblvul_2 = QtWidgets.QLabel(self.tabxss)
        self.lblvul_2.setGeometry(QtCore.QRect(370, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblvul_2.setFont(font)
        self.lblvul_2.setObjectName("lblvul_2")
        self.pbpages_2 = QtWidgets.QProgressBar(self.tabxss)
        self.pbpages_2.setGeometry(QtCore.QRect(50, 140, 531, 31))
        self.pbpages_2.setProperty("value", 24)
        self.pbpages_2.setObjectName("pbpages_2")
        self.pbtotal_2 = QtWidgets.QProgressBar(self.tabxss)
        self.pbtotal_2.setGeometry(QtCore.QRect(50, 240, 531, 31))
        self.pbtotal_2.setProperty("value", 24)
        self.pbtotal_2.setObjectName("pbtotal_2")
        self.lblpsp_2 = QtWidgets.QLabel(self.tabxss)
        self.lblpsp_2.setGeometry(QtCore.QRect(50, 110, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblpsp_2.setFont(font)
        self.lblpsp_2.setObjectName("lblpsp_2")
        self.lblpname_2 = QtWidgets.QLabel(self.tabxss)
        self.lblpname_2.setGeometry(QtCore.QRect(50, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblpname_2.setFont(font)
        self.lblpname_2.setObjectName("lblpname_2")
        self.btncancel_3 = QtWidgets.QPushButton(self.tabxss)
        self.btncancel_3.setGeometry(QtCore.QRect(540, 280, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncancel_3.sizePolicy().hasHeightForWidth())
        self.btncancel_3.setSizePolicy(sizePolicy)
        self.btncancel_3.setMinimumSize(QtCore.QSize(80, 35))
        self.btncancel_3.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btncancel_3.setFont(font)
        self.btncancel_3.setStyleSheet("border-radius: 5px;\n"
                                       "background-color:red;\n"
                                       "color:white;\n"
                                       "font-weight:bold;\n"
                                       "font-size: 13px;")
        self.btncancel_3.setObjectName("btncancel_3")
        self.lbltargetxss = QtWidgets.QLabel(self.tabxss)
        self.lbltargetxss.setGeometry(QtCore.QRect(50, 60, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(11)
        self.lbltargetxss.setFont(font)
        self.lbltargetxss.setText("")
        self.lbltargetxss.setObjectName("lbltargetxss")
        self.lbltsp_2 = QtWidgets.QLabel(self.tabxss)
        self.lbltsp_2.setGeometry(QtCore.QRect(50, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltsp_2.setFont(font)
        self.lbltsp_2.setObjectName("lbltsp_2")
        self.lbltotal_2 = QtWidgets.QLabel(self.tabxss)
        self.lbltotal_2.setGeometry(QtCore.QRect(530, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbltotal_2.setFont(font)
        self.lbltotal_2.setObjectName("lbltotal_2")
        self.tabWidget.addTab(self.tabxss, "")
        self.tabreport = QtWidgets.QWidget()
        self.tabreport.setObjectName("tabreport")
        self.lbltx = QtWidgets.QLabel(self.tabreport)
        self.lbltx.setGeometry(QtCore.QRect(190, 140, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbltx.setFont(font)
        self.lbltx.setText("")
        self.lbltx.setObjectName("lbltx")
        self.lbldisx = QtWidgets.QLabel(self.tabreport)
        self.lbldisx.setGeometry(QtCore.QRect(150, 140, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbldisx.setFont(font)
        self.lbldisx.setObjectName("lbldisx")
        self.gbxss = QtWidgets.QGroupBox(self.tabreport)
        self.gbxss.setGeometry(QtCore.QRect(19, 19, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbxss.setFont(font)
        self.gbxss.setStyleSheet("color:rgb(0, 170, 255)")
        self.gbxss.setObjectName("gbxss")
        self.listxss = QtWidgets.QListWidget(self.gbxss)
        self.listxss.setGeometry(QtCore.QRect(0, 20, 241, 101))
        self.listxss.setObjectName("listxss")
        self.gbdone = QtWidgets.QGroupBox(self.tabreport)
        self.gbdone.setGeometry(QtCore.QRect(360, 20, 241, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.gbdone.setFont(font)
        self.gbdone.setStyleSheet("")
        self.gbdone.setObjectName("gbdone")
        self.lbltotalpages = QtWidgets.QLabel(self.gbdone)
        self.lbltotalpages.setGeometry(QtCore.QRect(10, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltotalpages.setFont(font)
        self.lbltotalpages.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lbltotalpages.setText("")
        self.lbltotalpages.setTextFormat(QtCore.Qt.PlainText)
        self.lbltotalpages.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltotalpages.setObjectName("lbltotalpages")
        self.lbldistp = QtWidgets.QLabel(self.gbdone)
        self.lbldistp.setGeometry(QtCore.QRect(120, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbldistp.setFont(font)
        self.lbldistp.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lbldistp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbldistp.setObjectName("lbldistp")
        self.lbltotaltime = QtWidgets.QLabel(self.gbdone)
        self.lbltotaltime.setGeometry(QtCore.QRect(10, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltotaltime.setFont(font)
        self.lbltotaltime.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lbltotaltime.setText("")
        self.lbltotaltime.setTextFormat(QtCore.Qt.PlainText)
        self.lbltotaltime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltotaltime.setObjectName("lbltotaltime")
        self.lbltimetaken = QtWidgets.QLabel(self.gbdone)
        self.lbltimetaken.setGeometry(QtCore.QRect(120, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbltimetaken.setFont(font)
        self.lbltimetaken.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lbltimetaken.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltimetaken.setObjectName("lbltimetaken")
        self.lblwvp = QtWidgets.QLabel(self.gbdone)
        self.lblwvp.setGeometry(QtCore.QRect(10, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblwvp.setFont(font)
        self.lblwvp.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lblwvp.setText("")
        self.lblwvp.setTextFormat(QtCore.Qt.PlainText)
        self.lblwvp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblwvp.setObjectName("lblwvp")
        self.lbldiswvp = QtWidgets.QLabel(self.gbdone)
        self.lbldiswvp.setGeometry(QtCore.QRect(120, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbldiswvp.setFont(font)
        self.lbldiswvp.setStyleSheet("colo:rgb(0, 0, 0);")
        self.lbldiswvp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbldiswvp.setWordWrap(True)
        self.lbldiswvp.setObjectName("lbldiswvp")
        self.btnsave = QtWidgets.QPushButton(self.gbdone)
        self.btnsave.setGeometry(QtCore.QRect(40, 150, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnsave.setFont(font)
        self.btnsave.setToolTipDuration(1)
        self.btnsave.setStyleSheet("border-radius: 5px;\n"
                                   "background-color:green;\n"
                                   "color:white;\n"
                                   "font-weight:bold;\n"
                                   "font-size: 13px;")
        self.btnsave.setObjectName("btnsave")
        self.gbsqli = QtWidgets.QGroupBox(self.tabreport)
        self.gbsqli.setGeometry(QtCore.QRect(20, 170, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbsqli.setFont(font)
        self.gbsqli.setStyleSheet("color:rgb(0, 170, 255);")
        self.gbsqli.setObjectName("gbsqli")
        self.listsqli = QtWidgets.QListWidget(self.gbsqli)
        self.listsqli.setGeometry(QtCore.QRect(0, 20, 241, 101))
        self.listsqli.setObjectName("listsqli")
        self.lbltq = QtWidgets.QLabel(self.tabreport)
        self.lbltq.setGeometry(QtCore.QRect(190, 300, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbltq.setFont(font)
        self.lbltq.setText("")
        self.lbltq.setObjectName("lbltq")
        self.lbldisq = QtWidgets.QLabel(self.tabreport)
        self.lbldisq.setGeometry(QtCore.QRect(150, 300, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbldisq.setFont(font)
        self.lbldisq.setObjectName("lbldisq")
        self.btnnew = QtWidgets.QPushButton(self.tabreport)
        self.btnnew.setGeometry(QtCore.QRect(394, 250, 81, 31))
        self.btnnew.setStyleSheet("border-radius: 5px;\n"
                                  "background-color:rgb(0, 170, 255);\n"
                                  "color:white;\n"
                                  "font-weight:bold;\n"
                                  "font-size: 13px;")
        self.btnnew.setObjectName("btnnew")
        self.btnExit = QtWidgets.QPushButton(self.tabreport)
        self.btnExit.setGeometry(QtCore.QRect(484, 250, 81, 31))
        self.btnExit.setStyleSheet("border-radius: 5px;\n"
                                   "background-color:red;\n"
                                   "color:white;\n"
                                   "font-weight:bold;\n"
                                   "font-size: 13px;")
        self.btnExit.setObjectName("btnExit")
        self.tabWidget.addTab(self.tabreport, "")
        self.lbtar = QtWidgets.QLabel(self.centralwidget)
        self.lbtar.setGeometry(QtCore.QRect(30, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbtar.setFont(font)
        self.lbtar.setObjectName("lbtar")
        self.lbltarget = QtWidgets.QLabel(self.centralwidget)
        self.lbltarget.setGeometry(QtCore.QRect(100, 50, 381, 16))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro")
        font.setPointSize(11)
        self.lbltarget.setFont(font)
        self.lbltarget.setText("")
        self.lbltarget.setObjectName("lbltarget")
        self.lboption = QtWidgets.QLabel(self.centralwidget)
        self.lboption.setGeometry(QtCore.QRect(520, 50, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lboption.setFont(font)
        self.lboption.setText("")
        self.lboption.setObjectName("lboption")
        self.lblvulno = QtWidgets.QLabel(self.centralwidget)
        self.lblvulno.setGeometry(QtCore.QRect(530, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblvulno.setFont(font)
        self.lblvulno.setText("")
        self.lblvulno.setObjectName("lblvulno")
        self.lbldoneno = QtWidgets.QLabel(self.centralwidget)
        self.lbldoneno.setGeometry(QtCore.QRect(460, 180, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbldoneno.setFont(font)
        self.lbldoneno.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbldoneno.setText("")
        self.lbldoneno.setObjectName("lbldoneno")
        self.logo = QtWidgets.QGraphicsView(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(490, 0, 161, 121))
        self.logo.setStyleSheet("background:url(gui/small.png);"
                                "border: none;")
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 440, 441, 41))
        self.label.setObjectName("label")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)
        MainWindow2.setTabOrder(self.tabWidget, self.treeView)
        MainWindow2.setTabOrder(self.treeView, self.btncancel_2)
        MainWindow2.setTabOrder(self.btncancel_2, self.btncancel_3)
        MainWindow2.setTabOrder(self.btncancel_3, self.btncancel)
        MainWindow2.setTabOrder(self.btncancel, self.btnsave)
        MainWindow2.setTabOrder(self.btnsave, self.listxss)
        MainWindow2.setTabOrder(self.listxss, self.listsqli)
        MainWindow2.setTabOrder(self.listsqli, self.btnnew)
        MainWindow2.setTabOrder(self.btnnew, self.btnExit)
        MainWindow2.setTabOrder(self.btnExit, self.logo)
        self.tabsqli.setEnabled(False)
        self.tabxss.setEnabled(False)
        self.tabreport.setEnabled(False)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "WASec - [ScanOption]"))
        self.treeView.setStatusTip(_translate("MainWindow2", "Crawled links"))
        self.btncancel.setToolTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel.setStatusTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel.setText(_translate("MainWindow2", "Cancel"))
        self.lblstate_crawl.setText(_translate("MainWindow2", "Status:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcrawl), _translate("MainWindow2", "Crawl Site"))
        self.btncancel_2.setToolTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel_2.setStatusTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel_2.setText(_translate("MainWindow2", "Cancel"))
        self.lbltotal.setText(_translate("MainWindow2", "/"))
        self.lblpname.setText(_translate("MainWindow2", "Testing:"))
        self.lblpsp.setText(_translate("MainWindow2", "Page Scan Progress:"))
        self.lbltsp.setText(_translate("MainWindow2", "Total Scan Progress:"))
        self.lblsno.setText(_translate("MainWindow2", "Tested:"))
        self.lblvul.setText(_translate("MainWindow2", "Vulnerabilities:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabsqli),
                                  _translate("MainWindow2", "SQL Injection Scan"))
        self.lblsno_2.setText(_translate("MainWindow2", "Tested:"))
        self.lblvul_2.setText(_translate("MainWindow2", "Vulnerabilities:"))
        self.lblpsp_2.setText(_translate("MainWindow2", "Page Scan Progress:"))
        self.lblpname_2.setText(_translate("MainWindow2", "Testing:"))
        self.btncancel_3.setToolTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel_3.setStatusTip(_translate("MainWindow2", "Cancel crawling"))
        self.btncancel_3.setText(_translate("MainWindow2", "Cancel"))
        self.lbltsp_2.setText(_translate("MainWindow2", "Total Scan Progress:"))
        self.lbltotal_2.setText(_translate("MainWindow2", "/"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabxss), _translate("MainWindow2", "XSS Scan"))
        self.lbldisx.setText(_translate("MainWindow2", "Total:"))
        self.gbxss.setToolTip(_translate("MainWindow2", "XSS vulnerabilities found in your website"))
        self.gbxss.setTitle(_translate("MainWindow2", "XSS Vulnerabilities Found"))
        self.gbdone.setTitle(_translate("MainWindow2", "Done!"))
        self.lbldistp.setText(_translate("MainWindow2", "Crawled Pages"))
        self.lbltimetaken.setText(_translate("MainWindow2", "Time Taken"))
        self.lbldiswvp.setText(_translate("MainWindow2", "of Website is Vulnerable"))
        self.btnsave.setToolTip(_translate("MainWindow2", "Save a detailed report in XML"))
        self.btnsave.setStatusTip(_translate("MainWindow2", "Save a detailed report in XML"))
        self.btnsave.setWhatsThis(_translate("MainWindow2", "Save a detailed report in XML"))
        self.btnsave.setText(_translate("MainWindow2", "Save Detailed Report"))
        self.gbsqli.setToolTip(_translate("MainWindow2", "SQLi vulnerabilities found in your website"))
        self.gbsqli.setTitle(_translate("MainWindow2", "SQLi Vulnerabilities Found"))
        self.lbldisq.setText(_translate("MainWindow2", "Total:"))
        self.btnnew.setText(_translate("MainWindow2", "New Scan"))
        self.btnExit.setText(_translate("MainWindow2", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabreport),
                                  _translate("MainWindow2", "Evalation Report"))
        self.lbtar.setText(_translate("MainWindow2", "Target:"))
        self.label.setText(_translate("MainWindow2",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#5500ff;\">WASec is an open-source software developed under the GPL licence - 2018</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())

