# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

'''
    WASec – a software that performs automated tests on websites and scan them for SQL Injection and Cross-site Scripting Vulnerabilites.
    Copyright (c) 2018, Inass Husien.

    WASec is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation, either version 2 of the License or (at your option) any later version.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along with this program.
    If not, see <http://www.gnu.org/licenses/>

    You can contact us at e.ismail@it.misuratau.edu.ly
'''

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(688, 516)
        MainWindow2.setMinimumSize(QtCore.QSize(688, 516))
        MainWindow2.setMaximumSize(QtCore.QSize(688, 516))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow2.setWindowIcon(icon)
        MainWindow2.setIconSize(QtCore.QSize(60, 60))
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 100, 651, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(1)
        self.tabWidget.setStatusTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabcrawl = QtWidgets.QWidget()
        self.tabcrawl.setEnabled(True)
        self.tabcrawl.setObjectName("tabcrawl")
        self.treeView = QtWidgets.QTreeView(self.tabcrawl)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 641, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(641, 271))
        self.treeView.setMaximumSize(QtCore.QSize(641, 271))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.treeView.setFont(font)
        self.treeView.setStyleSheet("background:white;")
        self.treeView.setAutoExpandDelay(0)
        self.treeView.setItemsExpandable(False)
        self.treeView.setWordWrap(True)
        self.treeView.setHeaderHidden(True)
        self.treeView.setExpandsOnDoubleClick(False)
        self.treeView.setObjectName("treeView")
        self.btncrawlcancel = QtWidgets.QPushButton(self.tabcrawl)
        self.btncrawlcancel.setGeometry(QtCore.QRect(550, 280, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btncrawlcancel.sizePolicy().hasHeightForWidth())
        self.btncrawlcancel.setSizePolicy(sizePolicy)
        self.btncrawlcancel.setMinimumSize(QtCore.QSize(80, 35))
        self.btncrawlcancel.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btncrawlcancel.setFont(font)
        self.btncrawlcancel.setToolTip("")
        self.btncrawlcancel.setWhatsThis("")
        self.btncrawlcancel.setStyleSheet("border-radius: 5px;\n"
"background-color:red;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;\n"
"margin-bottom:5px;")
        self.btncrawlcancel.setObjectName("btncrawlcancel")
        self.label_2 = QtWidgets.QLabel(self.tabcrawl)
        self.label_2.setGeometry(QtCore.QRect(10, 290, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:blue;")
        self.label_2.setObjectName("label_2")
        self.lblshow_state = QtWidgets.QLabel(self.tabcrawl)
        self.lblshow_state.setGeometry(QtCore.QRect(70, 290, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblshow_state.setFont(font)
        self.lblshow_state.setWhatsThis("")
        self.lblshow_state.setText("")
        self.lblshow_state.setObjectName("lblshow_state")
        self.lbltotallinks = QtWidgets.QLabel(self.tabcrawl)
        self.lbltotallinks.setGeometry(QtCore.QRect(310, 289, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbltotallinks.setFont(font)
        self.lbltotallinks.setWhatsThis("")
        self.lbltotallinks.setStyleSheet("color:blue;")
        self.lbltotallinks.setText("")
        self.lbltotallinks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbltotallinks.setWordWrap(True)
        self.lbltotallinks.setObjectName("lbltotallinks")
        self.tabWidget.addTab(self.tabcrawl, "")
        self.tabsqli = QtWidgets.QWidget()
        self.tabsqli.setObjectName("tabsqli")
        self.lblpspsql = QtWidgets.QLabel(self.tabsqli)
        self.lblpspsql.setGeometry(QtCore.QRect(30, 90, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblpspsql.setFont(font)
        self.lblpspsql.setObjectName("lblpspsql")
        self.pbsqltotal = QtWidgets.QProgressBar(self.tabsqli)
        self.pbsqltotal.setGeometry(QtCore.QRect(30, 220, 591, 31))
        self.pbsqltotal.setWhatsThis("")
        self.pbsqltotal.setProperty("value", 0)
        self.pbsqltotal.setObjectName("pbsqltotal")
        self.lbltspsql = QtWidgets.QLabel(self.tabsqli)
        self.lbltspsql.setGeometry(QtCore.QRect(30, 180, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltspsql.setFont(font)
        self.lbltspsql.setObjectName("lbltspsql")
        self.btnsqlcancel = QtWidgets.QPushButton(self.tabsqli)
        self.btnsqlcancel.setGeometry(QtCore.QRect(540, 260, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnsqlcancel.sizePolicy().hasHeightForWidth())
        self.btnsqlcancel.setSizePolicy(sizePolicy)
        self.btnsqlcancel.setMinimumSize(QtCore.QSize(80, 35))
        self.btnsqlcancel.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnsqlcancel.setFont(font)
        self.btnsqlcancel.setWhatsThis("")
        self.btnsqlcancel.setStyleSheet("border-radius: 5px;\n"
"background-color:red;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnsqlcancel.setObjectName("btnsqlcancel")
        self.pbsqlpages = QtWidgets.QProgressBar(self.tabsqli)
        self.pbsqlpages.setGeometry(QtCore.QRect(30, 130, 591, 31))
        self.pbsqlpages.setWhatsThis("")
        self.pbsqlpages.setMaximum(0)
        self.pbsqlpages.setProperty("value", 0)
        self.pbsqlpages.setObjectName("pbsqlpages")
        self.lblsqltot = QtWidgets.QLabel(self.tabsqli)
        self.lblsqltot.setGeometry(QtCore.QRect(30, 270, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblsqltot.setFont(font)
        self.lblsqltot.setWhatsThis("")
        self.lblsqltot.setStyleSheet("color:blue;")
        self.lblsqltot.setObjectName("lblsqltot")
        self.lbltargetsql = QtWidgets.QLabel(self.tabsqli)
        self.lbltargetsql.setGeometry(QtCore.QRect(100, 20, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbltargetsql.setFont(font)
        self.lbltargetsql.setText("")
        self.lbltargetsql.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbltargetsql.setWordWrap(True)
        self.lbltargetsql.setObjectName("lbltargetsql")
        self.lblsqlname = QtWidgets.QLabel(self.tabsqli)
        self.lblsqlname.setGeometry(QtCore.QRect(30, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblsqlname.setFont(font)
        self.lblsqlname.setObjectName("lblsqlname")
        self.tabWidget.addTab(self.tabsqli, "")
        self.tabxss = QtWidgets.QWidget()
        self.tabxss.setObjectName("tabxss")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabxss)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnxsscancel = QtWidgets.QPushButton(self.tabxss)
        self.btnxsscancel.setGeometry(QtCore.QRect(540, 260, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnxsscancel.sizePolicy().hasHeightForWidth())
        self.btnxsscancel.setSizePolicy(sizePolicy)
        self.btnxsscancel.setMinimumSize(QtCore.QSize(80, 35))
        self.btnxsscancel.setMaximumSize(QtCore.QSize(80, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnxsscancel.setFont(font)
        self.btnxsscancel.setStyleSheet("border-radius: 5px;\n"
"background-color:red;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnxsscancel.setObjectName("btnxsscancel")
        self.lbltspxss = QtWidgets.QLabel(self.tabxss)
        self.lbltspxss.setGeometry(QtCore.QRect(30, 180, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbltspxss.setFont(font)
        self.lbltspxss.setObjectName("lbltspxss")
        self.pbxsstotal = QtWidgets.QProgressBar(self.tabxss)
        self.pbxsstotal.setGeometry(QtCore.QRect(30, 220, 591, 31))
        self.pbxsstotal.setProperty("value", 0)
        self.pbxsstotal.setObjectName("pbxsstotal")
        self.pbxsspages = QtWidgets.QProgressBar(self.tabxss)
        self.pbxsspages.setGeometry(QtCore.QRect(30, 130, 591, 31))
        self.pbxsspages.setMaximum(0)
        self.pbxsspages.setProperty("value", 0)
        self.pbxsspages.setObjectName("pbxsspages")
        self.lblpspxss = QtWidgets.QLabel(self.tabxss)
        self.lblpspxss.setGeometry(QtCore.QRect(30, 90, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblpspxss.setFont(font)
        self.lblpspxss.setObjectName("lblpspxss")
        self.lblxsstot = QtWidgets.QLabel(self.tabxss)
        self.lblxsstot.setGeometry(QtCore.QRect(30, 270, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblxsstot.setFont(font)
        self.lblxsstot.setStyleSheet("color:blue;")
        self.lblxsstot.setObjectName("lblxsstot")
        self.lbltargetxss = QtWidgets.QLabel(self.tabxss)
        self.lbltargetxss.setGeometry(QtCore.QRect(100, 20, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lbltargetxss.setFont(font)
        self.lbltargetxss.setText("")
        self.lbltargetxss.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbltargetxss.setWordWrap(True)
        self.lbltargetxss.setObjectName("lbltargetxss")
        self.lblxssname = QtWidgets.QLabel(self.tabxss)
        self.lblxssname.setGeometry(QtCore.QRect(30, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblxssname.setFont(font)
        self.lblxssname.setObjectName("lblxssname")
        self.tabWidget.addTab(self.tabxss, "")
        self.tabreport = QtWidgets.QWidget()
        self.tabreport.setObjectName("tabreport")
        self.gbxss = QtWidgets.QGroupBox(self.tabreport)
        self.gbxss.setGeometry(QtCore.QRect(19, 170, 331, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbxss.setFont(font)
        self.gbxss.setToolTip("")
        self.gbxss.setStyleSheet("color:rgb(0, 170, 255)")
        self.gbxss.setObjectName("gbxss")
        self.listxss = QtWidgets.QListWidget(self.gbxss)
        self.listxss.setGeometry(QtCore.QRect(0, 20, 321, 101))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.listxss.setFont(font)
        self.listxss.setStatusTip("")
        self.listxss.setStyleSheet("color:black;")
        self.listxss.setObjectName("listxss")
        self.lbldisx = QtWidgets.QLabel(self.gbxss)
        self.lbldisx.setGeometry(QtCore.QRect(0, 120, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbldisx.setFont(font)
        self.lbldisx.setStyleSheet("color:rgb(0, 170, 255);")
        self.lbldisx.setObjectName("lbldisx")
        self.lbltx = QtWidgets.QLabel(self.gbxss)
        self.lbltx.setGeometry(QtCore.QRect(40, 120, 221, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbltx.setFont(font)
        self.lbltx.setStyleSheet("color:black;")
        self.lbltx.setObjectName("lbltx")
        self.gbdone = QtWidgets.QGroupBox(self.tabreport)
        self.gbdone.setGeometry(QtCore.QRect(360, 20, 261, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.gbdone.setFont(font)
        self.gbdone.setStyleSheet("color:green;")
        self.gbdone.setObjectName("gbdone")
        self.lbltotalpages = QtWidgets.QLabel(self.gbdone)
        self.lbltotalpages.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltotalpages.setFont(font)
        self.lbltotalpages.setStyleSheet("color:black;")
        self.lbltotalpages.setTextFormat(QtCore.Qt.PlainText)
        self.lbltotalpages.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltotalpages.setObjectName("lbltotalpages")
        self.lbldistp = QtWidgets.QLabel(self.gbdone)
        self.lbldistp.setGeometry(QtCore.QRect(130, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbldistp.setFont(font)
        self.lbldistp.setStyleSheet("color:black;")
        self.lbldistp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbldistp.setObjectName("lbldistp")
        self.lbltotaltime = QtWidgets.QLabel(self.gbdone)
        self.lbltotaltime.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbltotaltime.setFont(font)
        self.lbltotaltime.setStyleSheet("color:black;")
        self.lbltotaltime.setTextFormat(QtCore.Qt.PlainText)
        self.lbltotaltime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltotaltime.setObjectName("lbltotaltime")
        self.lbltimetaken = QtWidgets.QLabel(self.gbdone)
        self.lbltimetaken.setGeometry(QtCore.QRect(130, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbltimetaken.setFont(font)
        self.lbltimetaken.setStyleSheet("color:black;")
        self.lbltimetaken.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltimetaken.setObjectName("lbltimetaken")
        self.lblwvp = QtWidgets.QLabel(self.gbdone)
        self.lblwvp.setGeometry(QtCore.QRect(10, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblwvp.setFont(font)
        self.lblwvp.setStyleSheet("color:black;")
        self.lblwvp.setTextFormat(QtCore.Qt.PlainText)
        self.lblwvp.setAlignment(QtCore.Qt.AlignCenter)
        self.lblwvp.setObjectName("lblwvp")
        self.lbldiswvp = QtWidgets.QLabel(self.gbdone)
        self.lbldiswvp.setGeometry(QtCore.QRect(130, 90, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbldiswvp.setFont(font)
        self.lbldiswvp.setStyleSheet("color:black;")
        self.lbldiswvp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbldiswvp.setWordWrap(True)
        self.lbldiswvp.setObjectName("lbldiswvp")
        self.btnsave = QtWidgets.QPushButton(self.gbdone)
        self.btnsave.setGeometry(QtCore.QRect(50, 150, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btnsave.setFont(font)
        self.btnsave.setToolTip("")
        self.btnsave.setToolTipDuration(1)
        self.btnsave.setWhatsThis("")
        self.btnsave.setStyleSheet("border-radius: 5px;\n"
"background-color:green;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnsave.setObjectName("btnsave")
        self.gbsqli = QtWidgets.QGroupBox(self.tabreport)
        self.gbsqli.setGeometry(QtCore.QRect(20, 10, 331, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gbsqli.setFont(font)
        self.gbsqli.setToolTip("")
        self.gbsqli.setStyleSheet("color:rgb(0, 170, 255);")
        self.gbsqli.setObjectName("gbsqli")
        self.listsqli = QtWidgets.QListWidget(self.gbsqli)
        self.listsqli.setGeometry(QtCore.QRect(0, 20, 331, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listsqli.sizePolicy().hasHeightForWidth())
        self.listsqli.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.listsqli.setFont(font)
        self.listsqli.setStatusTip("")
        self.listsqli.setStyleSheet("color:black;")
        self.listsqli.setObjectName("listsqli")
        self.lbldisq = QtWidgets.QLabel(self.gbsqli)
        self.lbldisq.setGeometry(QtCore.QRect(0, 125, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbldisq.setFont(font)
        self.lbldisq.setStyleSheet("color:rgb(0, 170, 255);")
        self.lbldisq.setObjectName("lbldisq")
        self.lbltq = QtWidgets.QLabel(self.gbsqli)
        self.lbltq.setGeometry(QtCore.QRect(40, 120, 221, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lbltq.setFont(font)
        self.lbltq.setStyleSheet("color:black;")
        self.lbltq.setObjectName("lbltq")
        self.btnnew = QtWidgets.QPushButton(self.tabreport)
        self.btnnew.setGeometry(QtCore.QRect(410, 240, 81, 31))
        self.btnnew.setStyleSheet("border-radius: 5px;\n"
"background-color:rgb(0, 170, 255);\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnnew.setObjectName("btnnew")
        self.btnExit = QtWidgets.QPushButton(self.tabreport)
        self.btnExit.setGeometry(QtCore.QRect(500, 240, 81, 31))
        self.btnExit.setStyleSheet("border-radius: 5px;\n"
"background-color:red;\n"
"color:white;\n"
"font-weight:bold;\n"
"font-size: 13px;")
        self.btnExit.setObjectName("btnExit")
        self.tabWidget.addTab(self.tabreport, "")
        self.lbtar = QtWidgets.QLabel(self.centralwidget)
        self.lbtar.setGeometry(QtCore.QRect(20, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbtar.setFont(font)
        self.lbtar.setObjectName("lbtar")
        self.lbltarget = QtWidgets.QLabel(self.centralwidget)
        self.lbltarget.setGeometry(QtCore.QRect(90, 20, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.lbltarget.setFont(font)
        self.lbltarget.setWhatsThis("")
        self.lbltarget.setText("")
        self.lbltarget.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbltarget.setWordWrap(True)
        self.lbltarget.setObjectName("lbltarget")
        self.logo = QtWidgets.QGraphicsView(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(520, 0, 161, 121))
        self.logo.setStyleSheet("background:url(gui/small.png);\n"
"border: none;")
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 440, 441, 41))
        self.label.setObjectName("label")
        self.lbloption = QtWidgets.QLabel(self.centralwidget)
        self.lbloption.setGeometry(QtCore.QRect(90, 60, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbloption.setFont(font)
        self.lbloption.setWhatsThis("")
        self.lbloption.setText("")
        self.lbloption.setObjectName("lbloption")
        self.lbtar_2 = QtWidgets.QLabel(self.centralwidget)
        self.lbtar_2.setGeometry(QtCore.QRect(20, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbtar_2.setFont(font)
        self.lbtar_2.setObjectName("lbtar_2")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)
        MainWindow2.setTabOrder(self.tabWidget, self.treeView)
        MainWindow2.setTabOrder(self.treeView, self.btnxsscancel)
        MainWindow2.setTabOrder(self.btnxsscancel, self.btncrawlcancel)
        MainWindow2.setTabOrder(self.btncrawlcancel, self.btnsave)
        MainWindow2.setTabOrder(self.btnsave, self.listxss)
        MainWindow2.setTabOrder(self.listxss, self.listsqli)
        MainWindow2.setTabOrder(self.listsqli, self.btnnew)
        MainWindow2.setTabOrder(self.btnnew, self.btnExit)
        MainWindow2.setTabOrder(self.btnExit, self.logo)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "WASec - [ScanOption]"))
        self.treeView.setStatusTip(_translate("MainWindow2", "Crawled links"))
        self.btncrawlcancel.setStatusTip(_translate("MainWindow2", " Stop crawling"))
        self.btncrawlcancel.setText(_translate("MainWindow2", "Cancel"))
        self.label_2.setText(_translate("MainWindow2", "Status:"))
        self.lblshow_state.setStatusTip(_translate("MainWindow2", "Crawler status"))
        self.lbltotallinks.setStatusTip(_translate("MainWindow2", "All links found in website"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcrawl), _translate("MainWindow2", "Crawl Site"))
        self.lblpspsql.setText(_translate("MainWindow2", "Page Scan Progress:"))
        self.pbsqltotal.setStatusTip(_translate("MainWindow2", "Total website testing progress"))
        self.lbltspsql.setText(_translate("MainWindow2", "Total Scan Progress:"))
        self.btnsqlcancel.setToolTip(_translate("MainWindow2", "Cancel crawling"))
        self.btnsqlcancel.setStatusTip(_translate("MainWindow2", "Stop Testing"))
        self.btnsqlcancel.setText(_translate("MainWindow2", "Cancel"))
        self.pbsqlpages.setStatusTip(_translate("MainWindow2", "Page is being scanned"))
        self.lblsqltot.setStatusTip(_translate("MainWindow2", "Vulnerabilities found"))
        self.lblsqltot.setText(_translate("MainWindow2", "Found"))
        self.lbltargetsql.setStatusTip(_translate("MainWindow2", "Link being tested"))
        self.lblsqlname.setText(_translate("MainWindow2", "Testing:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabsqli), _translate("MainWindow2", "SQL Injection Scan"))
        self.btnxsscancel.setToolTip(_translate("MainWindow2", "Cancel crawling"))
        self.btnxsscancel.setStatusTip(_translate("MainWindow2", "Stop testing"))
        self.btnxsscancel.setText(_translate("MainWindow2", "Cancel"))
        self.lbltspxss.setText(_translate("MainWindow2", "Total Scan Progress:"))
        self.pbxsstotal.setStatusTip(_translate("MainWindow2", "Total website testing progress"))
        self.pbxsspages.setStatusTip(_translate("MainWindow2", "Page is being scanned"))
        self.lblpspxss.setText(_translate("MainWindow2", "Page Scan Progress:"))
        self.lblxsstot.setStatusTip(_translate("MainWindow2", "Vulnerabilities found"))
        self.lblxsstot.setText(_translate("MainWindow2", "Found"))
        self.lbltargetxss.setStatusTip(_translate("MainWindow2", "Link being tested"))
        self.lblxssname.setText(_translate("MainWindow2", "Testing:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabxss), _translate("MainWindow2", "XSS Scan"))
        self.gbxss.setTitle(_translate("MainWindow2", "XSS Vulnerabilities Found"))
        self.lbldisx.setText(_translate("MainWindow2", "Total:"))
        self.lbltx.setText(_translate("MainWindow2", "N/A"))
        self.gbdone.setTitle(_translate("MainWindow2", "Done!"))
        self.lbltotalpages.setText(_translate("MainWindow2", "N/A"))
        self.lbldistp.setText(_translate("MainWindow2", "Crawled Pages"))
        self.lbltotaltime.setText(_translate("MainWindow2", "N/A"))
        self.lbltimetaken.setText(_translate("MainWindow2", "Time Taken"))
        self.lblwvp.setText(_translate("MainWindow2", "N/A"))
        self.lbldiswvp.setText(_translate("MainWindow2", "of Website is Vulnerable"))
        self.btnsave.setStatusTip(_translate("MainWindow2", "Save a detailed report in XML or Text file"))
        self.btnsave.setText(_translate("MainWindow2", "Save Detailed Report"))
        self.gbsqli.setTitle(_translate("MainWindow2", "SQLi Vulnerabilities Found"))
        self.lbldisq.setText(_translate("MainWindow2", "Total:"))
        self.lbltq.setText(_translate("MainWindow2", "N/A"))
        self.btnnew.setStatusTip(_translate("MainWindow2", "Start a new scan"))
        self.btnnew.setText(_translate("MainWindow2", "New Scan"))
        self.btnExit.setStatusTip(_translate("MainWindow2", "Exit WASec"))
        self.btnExit.setText(_translate("MainWindow2", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabreport), _translate("MainWindow2", "Evalation Report"))
        self.lbtar.setText(_translate("MainWindow2", "Target:"))
        self.lbltarget.setStatusTip(_translate("MainWindow2", "Tested website"))
        self.label.setText(_translate("MainWindow2", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#5500ff;\">WASec is an open-source software developed under the GPL licence - 2018</span></p></body></html>"))
        self.lbloption.setStatusTip(_translate("MainWindow2", "Scan option"))
        self.lbtar_2.setText(_translate("MainWindow2", "Option:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec_())

